version: '3.3'
services:

  odoo:
    container_name: odoo_TFG_Produccion
    image: odoo:15.0
    restart: unless-stopped 
    depends_on:
      - postgres
    ports:
      - "8300:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./conf:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo

  postgres:
    container_name: postgres
    image: postgres:14.0

    restart: unless-stopped       
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  odoo-data:
  db-data: